### ISSUE TITLE
Don't update the map every time unit moves

### ISSUE THREAD

**Issue by axx0** [axx0/Civ2-clone#106]
Map seems to be redrawn every time a unit moves, even if it moves within the view

**Comment by reubene** [comment]
It shouldn't be line 49 in base game view recycles the base image and animations, if it's redrawing every new animation there is a bug of some kind

**Comment by axx0** [comment]
I believe IsInSameArea function is returning false when you move the unit and thus it redraws the map. I tried analyzing it some weeks ago but couldn't get to the bottom of it.
