### ISSUE TITLE
Missing references - Broken code

### ISSUE THREAD

**Issue by delcantao** [axx0/Civ2-clone#111]
Hi guys,

I am trying to run the project but it seems like is missing a lot of dependencies and imports in the code that is in master branch, primarily related to the EtoFormsUI, especially the Ruleset class.

Am I doing something wrong? After importing the missing files, a lot of other errors happened.

I tried reverting to one commit prior, yet the issue persisted. Going back two commits altered the error; the Ruleset class was no longer missing, but now the EtoFormsUI.LocalPlayer class does not implement all the interface members.

I can't even run the project. It's frustrating. I love this game.

Can someone shed some light on my path?

I appreciate that

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'MenuElement' could not be found (are you missing a using directive or an assembly reference?)	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Players\Orders\ImprovementOrder.cs	20	Active
Error	CS0246	The type or namespace name 'Ruleset' could not be found (are you missing a using directive or an assembly reference?)	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Bitmaps\ImageLoader\TerrainLoader.cs	14	Active
Error	CS0246	The type or namespace name 'Ruleset' could not be found (are you missing a using directive or an assembly reference?)	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Bitmaps\ImageLoader\TerrainLoader.cs	27	Active
Error	CS0246	The type or namespace name 'Ruleset' could not be found (are you missing a using directive or an assembly reference?)	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Bitmaps\ImageLoader\UnitLoader.cs	15	Active
Error	CS0246	The type or namespace name 'Ruleset' could not be found (are you missing a using directive or an assembly reference?)	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Bitmaps\Images.ImportBitmaps.cs	16	Active
Error	CS0246	The type or namespace name 'Ruleset' could not be found (are you missing a using directive or an assembly reference?)	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Bitmaps\Images.ImportBitmaps.cs	45	Active
Error	CS0246	The type or namespace name 'Ruleset' could not be found (are you missing a using directive or an assembly reference?)	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Bitmaps\Images.ImportBitmaps.cs	147	Active
Error	CS0246	The type or namespace name 'Ruleset' could not be found (are you missing a using directive or an assembly reference?)	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Bitmaps\Images.ImportBitmaps.cs	172	Active
Error	CS0246	The type or namespace name 'PlayerColour' could not be found (are you missing a using directive or an assembly reference?)	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Bitmaps\MapImages.cs	15	Active
Error	CS0246	The type or namespace name 'Ruleset' could not be found (are you missing a using directive or an assembly reference?)	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Main.ShowPopupBox.cs	17	Active
Error	CS0535	'LocalPlayer' does not implement interface member 'IPlayer.MapChanged(List<Tile>)'	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Players\LocalPlayer.cs	14	Active
Error	CS0535	'LocalPlayer' does not implement interface member 'IPlayer.WaitingAtEndOfTurn()'	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Players\LocalPlayer.cs	14	Active
Error	CS0535	'LocalPlayer' does not implement interface member 'IPlayer.Civilization'	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Players\LocalPlayer.cs	14	Active
Error	CS0535	'LocalPlayer' does not implement interface member 'IPlayer.Ui'	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Players\LocalPlayer.cs	14	Active
Error	CS0246	The type or namespace name 'Ruleset' could not be found (are you missing a using directive or an assembly reference?)	EtoFormsUI	C:\Users\feedc\Source\Repos\Civ2-clone\EtoFormsUI\EtoFormsUI\Bitmaps\ImageLoader\CityLoader.cs	13	Active

**Comment by axx0** [comment]
We're still transitioning from Eto to raylib UI. So Eto folder is there untill this process is over, then we'll remove it. But you should be able to compile, you have to point to RaylibUI folder.
