### ISSUE TITLE
Search paths don't have the local sav/scn folder

### ISSUE THREAD

**Issue by axx0** [axx0/Civ2-clone#120]
When extracting bitmap data here
https://github.com/axx0/Civ2-clone/blob/698c18b92b6a4b1849c8363a44894c1aaa9161b0/RaylibUtils/Images.ImportBitmaps.cs#L113C25-L113C129

**Comment by reubene** [comment]
Yes, it needs to be using the ruleset which has the paths set correctly. Settings.SearchPaths is only really for use in the menus
