### ISSUE TITLE
Raylib-cs and .net8

### ISSUE THREAD

**Issue by reubene** [axx0/Civ2-clone#121]
Raylib-cs is in maintenance mode and probably won't be updated fro .net8 but .net6 goes out of support later this year. 

Perhaps we should evaluate moving to https://github.com/MrScautHD/Raylib-CSharp

**Comment by axx0** [comment]
Ok I agree we should try it out. Let me know if you'll be working on this, otherwise I'll get to it when I have more time.

**Comment by reubene** [comment]
I'm not currently working on this still looking at the city window and savegames.

**Comment by axx0** [comment]
I made changes for the new library. Everything seems to be working fine on my end. Please try it out.

**Comment by reubene** [comment]
I've been working with this and it doesn't seem to have caused any issues, will close
