### ISSUE TITLE
Make File.Exists case insensitive for linux (gtk)

### ISSUE THREAD

**Issue by axx0** [axx0/Civ2-clone#28]
(for .txt files like Game/game, Labels/labels, etc.)
See here:
https://github.com/axx0/Civ2-clone/blob/589361d6ff9be5f761bbc4869e0e1b77c1dbbee3/Engine/src/Utils.cs#L27-L62
Windows (WinForms) doesn't have this problem.

**Comment by Lewiscowles1986** [comment]
If you are in-charge of extracting assets, maybe a one-time upon boot change to the files to be consistently lowercase or uppercase would avoid the need to worry about this during the game?

**Comment by axx0** [comment]
You mean scanning all the files and changing their case? I'll have to think about it, I'm more in favour of programmatically ignoring the case instead of changing the actual names of files. (or did I misinterpret what you wrote?)

**Comment by Lewiscowles1986** [comment]
I was suggesting a one-time action of scanning files when extracting (so you'd already be scanning them), but converting their saved paths to be lowercase (or uppercase, consistent casing is the core of this).

**Comment by axx0** [comment]
I did some adjustments so that it can read files on Linux, even when files are upper/lower case.
