### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by axx0** [axx0/Civ2-clone#55]
Raylib uses a font which doesn't look anything like the one from the original game and thus needs to be changed.
Civ2 uses 2 fonts: Times new roman + Arial

So we can either
- use a free font from the web (get something from e.g. google fonts which looks like the original font)
- search and pull fonts built-in in win/max/linux/etc.

Your thoughts please.

**Comment by reubene** [comment]
My latest commit includes a copy of times new roman, it works but I've not checked to see if it being used in the right places. 

I have a few more things to get working before I make a PR

**Comment by axx0** [comment]
> My latest commit includes a copy of times new roman, it works but I've not checked to see if it being used in the right places.
> 
> I have a few more things to get working before I make a PR

OK, I think we'll be needing Arial fonts additionally.
You're making good progress, if there's any help you need that doesn't interfere with your work please make an issue.

**Comment by axx0** [comment]
lgtm
