### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by einarpersson** [axx0/Civ2-clone#58]
Hi! 

Just found this:) It would be helpful if just a bit more information could be added in the README on how to get started.

- how to install/build
- prerequisites
- also maybe:
  - status of project. Is it pretty much complete?
  - extensibility? What does Lua-support mean? Etc.

Thanks!

**Comment by axx0** [comment]
Hi, we'll probably update the readme once we get at least some pre-alpha gameplay going. Right now we're in the process of changing game engines and it's been rather slow. Lots of ToT scenarios have been extensively modded with Lua over the years. This clone should be able to correctly play those scenarios with Lua support in mind.

**Comment by axx0** [comment]
Updated, we'll add more info along the way....
