### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by axx0** [axx0/Civ2-clone#61]
There's an ever increasing memory consumption when moving through the map.
There could be an issue with loading of this texture.
![image](https://github.com/axx0/Civ2-clone/assets/21365802/179566e8-bf7c-4c31-9695-5bed221479bc)

**Comment by reubene** [comment]
I'm rewriting part of this code to handle animations etc... this should be cleaned up by that work

**Comment by reubene** [comment]
This should be fixed by my latest PR I'm now sharing the background images where I can and unloading them when no longer in use
