### ISSUE TITLE
Move animation moves slightly too far

### ISSUE THREAD

**Issue by reubene** [axx0/Civ2-clone#71]
Noticed this just before, have not investigated why I think there might be a mistake in the maths

**Comment by axx0** [comment]
Have you fixed this? I do remember this being an issue, but I can't reproduce it now.

**Comment by reubene** [comment]
I've reworked a lot of things in this area, I'll retest it in the next few days and close if I can't reproduce.  I think it might have been an integer rounding problem which may have gone away when I switched all calculations to floating point vectors

**Comment by reubene** [comment]
I can't reproduce this anymore so I'll close it

**Comment by axx0** [comment]
I noticed this again when testing TOT.
