### ISSUE TITLE
Test of Time DLL images

### ISSUE THREAD

**Issue by reubene** [axx0/Civ2-clone#77]
I tried pointing the app at a copy of TOT it didn't go well, we probably should support loading the images from the TOT DLLs as well

**Comment by axx0** [comment]
I didn't go beyond main menu, but it should load the starting image correctly now.
The starting dialog is actually @ STARTMENU, but I can't put that class in the dialogs folder since MGE interface won't work then (STARTMENU doesn't appear in Game.txt for MGE).

**Comment by reubene** [comment]
If it's a dialog that's only in TOT it should probably only be in the TOT project.  I've made that work will have a PR for it shortly. 

I don't like the TOT MainMenu i don't think it's very useful to front load those scenarios this is an area I might suggest we deviate from the source

**Comment by axx0** [comment]
ok I agree
