### ISSUE TITLE
Civ II: Test of Time support

### ISSUE THREAD

**Issue by axx0** [axx0/Civ2-clone#8]
Stlye-wise it looks like a different game, but except for some new features the base game is the same as classic Civ 2.

**Comment by reubene** [comment]
I'm looking at starting work on this, but I don't want to duplicate effort. Do you had any plans to work on this?

Thanks

**Comment by axx0** [comment]
I planned on adding a path to ToT folder in appsettings.json and perhaps making another parameter there which would determine which game to start (if paths to Civ2 MGE & ToT both exist). Then enable just loading of a ToT sav game and supporting 64x64 units etc. ToT was never my thing so I would need to learn more of its differences vs Civ2MGE before making bigger plans.
Anyway you're more than welcome to start on this. ToT support is quite important for guys on civfanatics.
