### ISSUE TITLE
Feature Request: use Bilinear/Bicubic interpolation scaling on zooming

### ISSUE THREAD

**Issue by IVENEND** [axx0/Civ2-clone#82]
Hello. First of all, I post here since it seems that Github is the only active place of the Civ2 clone project. I'm sorry if the Issues section is not the right place to post feature requests.

One thing that Civ2 bugs me is it use [nearest-neighbor interpolation](https://en.wikipedia.org/wiki/Image_scaling) scaling when zooming in/out. This cause two problems:

First, graphic looks pixelated when zooming in. Back in 1999, when played Civ2 with a CRT screen, this problem was inconspicuous since CRT screens have built-in anti-aliasing. But this problem becomes obvious when using a modern LCD screen.

Pixelated graphic when zooming in:
![1](https://github.com/axx0/Civ2-clone/assets/43954515/2d1a3214-55cd-4715-aee5-edd77512bfce)

Second, a even more serious problem cause by nearest-neighbor interpolation is that, graphics distorted when doing non-integer scaling. And all unit graphic in UI of Civ2 are scaling non-integerly.

Here you can see the pikes and lances (which supposed to be straight) of the units are seriously distorted:
![2](https://github.com/axx0/Civ2-clone/assets/43954515/87749bbc-fc9e-40a5-bd3a-c8fccdae42ac)

Using bilinear/bicubic interpolation scaling on zooming can fix the problem. So I request that, if possible, add an option to enable bilinear/bicubic interpolation scaling in the Civ2-clone project.

Thanks for reading my post!

**Comment by axx0** [comment]
Hi,
Raylib offers these options for texture filtering:

![Clipboard02](https://github.com/axx0/Civ2-clone/assets/21365802/f44316ff-e4c7-4d1e-9e18-547d7e396cc1)

Doing:
a) point ("no filter, just pixel approximation")
b) bilinear ("linear filtering")
c) trilinear
with 8 scaling factors (1, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75) I get these results:

![Clipboard](https://github.com/axx0/Civ2-clone/assets/21365802/710563d4-4a3d-4867-bd9f-6303d1e098e1)

There are probably more options for texture graphics in raylib.
Does this help?

**Comment by IVENEND** [comment]
> Hi, Raylib offers these options for texture filtering:
> 
> ![Clipboard02](https://private-user-images.githubusercontent.com/21365802/289313499-f44316ff-e4c7-4d1e-9e18-547d7e396cc1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU0ODAsIm5iZiI6MTcwMjE5NTE4MCwicGF0aCI6Ii8yMTM2NTgwMi8yODkzMTM0OTktZjQ0MzE2ZmYtZTRjNy00ZDFlLTllMTgtNTQ3ZDdlMzk2Y2MxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA3NTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZDQzODY3OGQxMTI4YWE2OWM0YTYzNDVmNzFlMGNiZTIyM2Q1ZTg2MDRmYzI0NmI1Zjg3MjU2MTFiM2EwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20uA-vlQsq9bml2bVa9630ryDEVoK58HKRfpR8NXQlk) [ ![Clipboard02](https://private-user-images.githubusercontent.com/21365802/289313499-f44316ff-e4c7-4d1e-9e18-547d7e396cc1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU0ODAsIm5iZiI6MTcwMjE5NTE4MCwicGF0aCI6Ii8yMTM2NTgwMi8yODkzMTM0OTktZjQ0MzE2ZmYtZTRjNy00ZDFlLTllMTgtNTQ3ZDdlMzk2Y2MxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA3NTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZDQzODY3OGQxMTI4YWE2OWM0YTYzNDVmNzFlMGNiZTIyM2Q1ZTg2MDRmYzI0NmI1Zjg3MjU2MTFiM2EwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20uA-vlQsq9bml2bVa9630ryDEVoK58HKRfpR8NXQlk) ](https://private-user-images.githubusercontent.com/21365802/289313499-f44316ff-e4c7-4d1e-9e18-547d7e396cc1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU0ODAsIm5iZiI6MTcwMjE5NTE4MCwicGF0aCI6Ii8yMTM2NTgwMi8yODkzMTM0OTktZjQ0MzE2ZmYtZTRjNy00ZDFlLTllMTgtNTQ3ZDdlMzk2Y2MxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA3NTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZDQzODY3OGQxMTI4YWE2OWM0YTYzNDVmNzFlMGNiZTIyM2Q1ZTg2MDRmYzI0NmI1Zjg3MjU2MTFiM2EwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20uA-vlQsq9bml2bVa9630ryDEVoK58HKRfpR8NXQlk) [ ](https://private-user-images.githubusercontent.com/21365802/289313499-f44316ff-e4c7-4d1e-9e18-547d7e396cc1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU0ODAsIm5iZiI6MTcwMjE5NTE4MCwicGF0aCI6Ii8yMTM2NTgwMi8yODkzMTM0OTktZjQ0MzE2ZmYtZTRjNy00ZDFlLTllMTgtNTQ3ZDdlMzk2Y2MxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA3NTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZDQzODY3OGQxMTI4YWE2OWM0YTYzNDVmNzFlMGNiZTIyM2Q1ZTg2MDRmYzI0NmI1Zjg3MjU2MTFiM2EwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20uA-vlQsq9bml2bVa9630ryDEVoK58HKRfpR8NXQlk)
> 
> Doing: a) point ("no filter, just pixel approximation") b) bilinear ("linear filtering") c) trilinear with 8 scaling factors (1, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75) I get these results:
> 
> ![Clipboard](https://private-user-images.githubusercontent.com/21365802/289313561-710563d4-4a3d-4867-bd9f-6303d1e098e1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU0ODAsIm5iZiI6MTcwMjE5NTE4MCwicGF0aCI6Ii8yMTM2NTgwMi8yODkzMTM1NjEtNzEwNTYzZDQtNGEzZC00ODY3LWJkOWYtNjMwM2QxZTA5OGUxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA3NTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNTBlYjcwYTBkY2VmMjE4OWZjMDMyNzI5NDM0MDgxZWVkY2U0MTBhMzY1YzVjNDA0YzIwNDBjMzMzYjQ3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kSyQzNtER60y1UUB8vgbh03yPH8p_JVJ4tDucqQxVyA) [ ![Clipboard](https://private-user-images.githubusercontent.com/21365802/289313561-710563d4-4a3d-4867-bd9f-6303d1e098e1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU0ODAsIm5iZiI6MTcwMjE5NTE4MCwicGF0aCI6Ii8yMTM2NTgwMi8yODkzMTM1NjEtNzEwNTYzZDQtNGEzZC00ODY3LWJkOWYtNjMwM2QxZTA5OGUxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA3NTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNTBlYjcwYTBkY2VmMjE4OWZjMDMyNzI5NDM0MDgxZWVkY2U0MTBhMzY1YzVjNDA0YzIwNDBjMzMzYjQ3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kSyQzNtER60y1UUB8vgbh03yPH8p_JVJ4tDucqQxVyA) ](https://private-user-images.githubusercontent.com/21365802/289313561-710563d4-4a3d-4867-bd9f-6303d1e098e1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU0ODAsIm5iZiI6MTcwMjE5NTE4MCwicGF0aCI6Ii8yMTM2NTgwMi8yODkzMTM1NjEtNzEwNTYzZDQtNGEzZC00ODY3LWJkOWYtNjMwM2QxZTA5OGUxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA3NTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNTBlYjcwYTBkY2VmMjE4OWZjMDMyNzI5NDM0MDgxZWVkY2U0MTBhMzY1YzVjNDA0YzIwNDBjMzMzYjQ3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kSyQzNtER60y1UUB8vgbh03yPH8p_JVJ4tDucqQxVyA) [ ](https://private-user-images.githubusercontent.com/21365802/289313561-710563d4-4a3d-4867-bd9f-6303d1e098e1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU0ODAsIm5iZiI6MTcwMjE5NTE4MCwicGF0aCI6Ii8yMTM2NTgwMi8yODkzMTM1NjEtNzEwNTYzZDQtNGEzZC00ODY3LWJkOWYtNjMwM2QxZTA5OGUxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA3NTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNTBlYjcwYTBkY2VmMjE4OWZjMDMyNzI5NDM0MDgxZWVkY2U0MTBhMzY1YzVjNDA0YzIwNDBjMzMzYjQ3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kSyQzNtER60y1UUB8vgbh03yPH8p_JVJ4tDucqQxVyA)
> 
> There are probably more options for texture graphics in raylib. Does this help?

Thanks for the reply. Of course that help! That is exactly what I talked about.

Personally I prefer bilinear/trilinear filtering (both actually look almost the same in the context of Civ2). But the best way might be adding different filtering as options in settings, in case some players prefer the old "sharp pixel" look of point filtering.

**Comment by axx0** [comment]
Adding this as option shouldn't be a problem. I'll keep this issue open until we get there.

**Comment by crhy** [comment]
THIS IS SO AWESOME!  Best game ever and finally a version that might be playable on modern hardware?!?!  Let me know if you want artwork to recreate it as a fully FOSS stand alone.  I'm down to help.

**Comment by axx0** [comment]
You mean using custom resources so we're not dependent on the original's artwork?

**Comment by crhy** [comment]
Yes exactly!  The original art is not great anyway, and I'm pretty handy in the GIMP.  Would love to do a retexture, then we could eventually come up with a fully FOSS release.

**Comment by crhy** [comment]
We could just use AI image creation.  Would be hyper fast I bet.

**Comment by crhy** [comment]
I've redone most of the assets in the game already.  Just waiting for an upload folder.  Going to look WAY better. :)  AND we can go full FOSS!  :D

**Comment by axx0** [comment]
@IVENEND I've finally added option for texture filtering in settings .json file.
Example (TextFilter=0 is left, TextFilter=2 is right)
![02](https://github.com/axx0/Civ2-clone/assets/21365802/9801ad67-2ee9-4486-ad4b-f6a6b556b5c5)

**Comment by crhy** [comment]
AWESOME!  But bear in mind that the new artwork is MUCH higher res, so this may not be as essential moving forward.  Anyway: YAY PROGRESS!  <3

**Comment by IVENEND** [comment]
Thank you so much!
