### ISSUE TITLE
Update dialog tiles when loading game/scenario

### ISSUE THREAD

**Issue by axx0** [axx0/Civ2-clone#98]
We need to update the look of dialogs when loading a .sav or scenarios which have custom dialog and icon pictures.
Currently `ImageUtils.SetLook(main.ActiveInterface);` is only set at beginning of game in MainMenu.cs and left as-is.

For example, the wallpaper for TOT's status panel should be different for what's currently implemented (the icons.gif in TOT root directory is from MGE, the game should look for icon file in the local folder or one of the "fallback" folders (Original, Fantasy, SciFi)).

**Comment by reubene** [comment]
I think I have a solution for this, it should also change if the user selects a TOT vs MPG ruleset when starting a new game

**Comment by reubene** [comment]
I think my recent changes to ensure the interface matches the selected ruleset fix this issue. Do you see any instances where this is still a problem?

**Comment by axx0** [comment]
I'll check.
