### ISSUE TITLE
Update status panel

### ISSUE THREAD

**Issue by axx0** [axx0/Civ2-clone#99]
Population, gold, info etc. need to be added to status panel. Offsets of what's currently drawn also needs to be updated.
I'll try to deal with this.

**Comment by reubene** [comment]
Thanks, could you include turn number in this as well? like in civ UIA

I don't think this section changes between views so probably can be coded directly with the panel. similar to what was in the Eto version

**Comment by axx0** [comment]
Ok I'll add it.

**Comment by axx0** [comment]
This is mostly done now.
